# Generated by Django 5.2.7 on 2026-02-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_notaventa_cliente_notaventa_comuna_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallenota',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
