# Generated by Django 5.2.7 on 2026-02-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_detallenota_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallenota',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
