# Generated by Django 5.2.7 on 2026-02-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_detallenota_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallenota',
            old_name='cantidad',
            new_name='cantidad_solicitada',
        ),
        migrations.RemoveField(
            model_name='detallenota',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='detallenota',
            name='producto',
        ),
        migrations.AddField(
            model_name='detallenota',
            name='capacidad_x_caja',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detallenota',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detallenota',
            name='descripcion',
            field=models.TextField(default='Sin descripción', max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallenota',
            name='dun',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detallenota',
            name='ean',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detallenota',
            name='formato_venta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detallenota',
            name='importe_a_facturar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='detallenota',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='detallenota',
            name='precio_x_caja',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='notaventa',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='notaventa',
            name='neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='notaventa',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
