# Generated by Django 4.2.27 on 2026-02-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_rename_cantidad_detallenota_cantidad_solicitada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaventa',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notaventa',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notaventa',
            name='giro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notaventa',
            name='hora_entrega',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notaventa',
            name='lugar_de_entrega',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notaventa',
            name='persona_responsable',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notaventa',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
