# Generated by Django 4.2.27 on 2026-02-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_notaventa_ciudad_notaventa_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaventa',
            name='tipo_bodega',
            field=models.CharField(blank=True, choices=[('bsf', 'Bodega BSF'), ('central', 'Bodega Central')], max_length=20, null=True),
        ),
    ]
