# Generated by Django 5.2.7 on 2026-03-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_alter_notaventa_tipo_bodega'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaventa',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('finalizada', 'Finalizada')], default='borrador', max_length=20),
        ),
    ]
