# Generated by Django 5.2.7 on 2026-03-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_notaventa_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaventa',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('finalizada', 'Finalizada'), ('despachada', 'Despachada')], default='borrador', max_length=20),
        ),
    ]
