# Generated by Django 5.2.7 on 2026-03-04 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_alter_notaventa_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('bodegabsf', 'Bodega BSF'), ('bodegacentral', 'Bodega Central'), ('pedidos', 'Gestión de Pedidos'), ('reportes', 'Reportes'), ('admin', 'Panel Administrativo')], max_length=50)),
                ('can_view', models.BooleanField(default=False, help_text='Ver/Consultar datos')),
                ('can_create', models.BooleanField(default=False, help_text='Crear nuevos registros')),
                ('can_edit', models.BooleanField(default=False, help_text='Editar registros existentes')),
                ('can_delete', models.BooleanField(default=False, help_text='Eliminar registros')),
                ('can_export', models.BooleanField(default=False, help_text='Exportar datos')),
                ('can_report', models.BooleanField(default=False, help_text='Generar reportes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de Módulo de Usuario',
                'verbose_name_plural': 'Permisos de Módulos de Usuarios',
                'unique_together': {('user', 'module')},
            },
        ),
    ]
