# Generated by Django 5.2.7 on 2026-03-04 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_usermodulepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConnectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_module', models.CharField(blank=True, default='', max_length=120)),
                ('current_path', models.CharField(blank=True, default='', max_length=255)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado de Conexión de Usuario',
                'verbose_name_plural': 'Estados de Conexión de Usuarios',
            },
        ),
    ]
