# Generated by Django 4.2.27 on 2026-03-04 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_userconnectionstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuiebresStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(max_length=350)),
                ('cantidad_solicitada', models.PositiveIntegerField()),
                ('cantidad_entregada', models.PositiveIntegerField()),
                ('cantidad_faltante', models.PositiveIntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiebres_stock', to='pedidos.detallenota')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiebres_stock', to='pedidos.notaventa')),
            ],
            options={
                'verbose_name': 'Quiebre de Stock',
                'verbose_name_plural': 'Quiebres de Stock',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
