# Generated by Django 5.2.7 on 2025-12-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodegabsf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsf',
            name='cant_solicitada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bsf',
            name='pedido',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
